config/routes.rb
OutumMonitor::Application.routes.draw do
  get "home/version"
  get "home/index"
  get "home/patch"

  resources :products do
    member do
      match 'download'
      match 'up'
      match 'down'
    end
  end

  devise_for :users

  resources :videos do
    member do
      match 'up'
      match 'down'
    end
  end

  resources :photos do
    member do
      match 'up'
      match 'down'
    end
  end

  get "monitor/all"

  get "monitor/online"

  resources :clients do
    resources :records
  end

  mount Outum::API => '/'

  root :to => 'home#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :note, :title
  has_many :attachments, as: :attachmentable, dependent: :destroy

  acts_as_list
  default_scope order('position')

  def video_attachment
    attachments.find_by_file_type "video"
  end

  def photo_attachment
    attachments.find_by_file_type "image"
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  before_filter :authenticate_user!, only: [:index, :edit, :new]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @controller = controller_name
    @action = action_name
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        Attachment.create(media: params[:photo_attachment], attachmentable: @video) if params[:photo_attachment]
        Attachment.create(media: params[:video_attachment], attachmentable: @video)if params[:video_attachment]

        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /video/1/up
  def up
    @video = Video.find(params[:id])
    @video.move_higher
    
    respond_to do |format|
      format.html { redirect_to videos_url, notice: "video #{@video.title} was successfully moved." }
    end
  end
  
  # PUT /video/1/down
  def down
    @video = Video.find(params[:id])
    @video.move_lower
    
    respond_to do |format|
      format.html { redirect_to videos_url, notice: "video #{@video.title} position was successfully moved." }
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])

        if params[:photo_attachment]
          @video.photo_attachment.delete if @video.photo_attachment
          Attachment.create(media: params[:photo_attachment], attachmentable: @video) 
        end

        if params[:video_attachment]
          @video.video_attachment.delete if @video.video_attachment
          Attachment.create(media: params[:video_attachment], attachmentable: @video)          
        end

        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for @video, :html => { :class => 'form-horizontal', multipart: true } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :note, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :note, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "图片", :class => 'control-label' %>
    <div class="controls">
      <%= file_field_tag :photo_attachment%>
      <%= image_tag(@video.photo_attachment.media.thumb) if @video.photo_attachment %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "视频", :class => 'control-label' %>
    <div class="controls">
      <%= file_field_tag :video_attachment%>
      <%= @video.video_attachment.media if @video.video_attachment %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                videos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<%- model_class = Video -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/videos/index.html.erb
<%- model_class = Video -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>图片</th>
      <th>视频</th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= link_to(image_tag(video.photo_attachment.media.thumb), video_path(video)) if video.photo_attachment %></td>
        <td><%= video.video_attachment.file_name if video.video_attachment %></td>
        <td><%= video.title %></td>
        <td><%=l video.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_video_path(video), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      video_path(video),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
          <a class="btn" href="<%= up_video_path(video) %>"><i class="icon-arrow-up"></i></a>
          <a class="btn" href="<%= down_video_path(video) %>"><i class="icon-arrow-down"></i></a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_video_path,
            :class => 'btn btn-primary' %>

app/views/videos/new.html.erb
<%- model_class = Video -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/videos/show.html.erb
<% content_for :head do %>
<%= meta_tag('video-url', @video.video_attachment.media_url) if @video.video_attachment %>
<% end %>

<%- model_class = Video -%>

<div class="container">
  <ul class="breadcrumb">
    <li><a href="/"><span class="label label-success">主页</span></a><span class="divider">/</span></li>
    <li class="active"><span class="label label-default">视频播放</span></li>
  </ul>
  <div class="page-header">
    <h1><%= @video.title %></h1>
  </div>

  <p class="lead"><%= raw @video.note %></p>

  <div id="player">
    <div class="watch">
      <a class="btn btn-primary">Click to Play Video ▶</a>
    </div>
    <%= render 'shared/player' %>
  </div>

</div>