config/routes.rb
OutumMonitor::Application.routes.draw do
  get "home/version"
  get "home/index"
  get "home/patch"

  resources :products do
    member do
      match 'download'
      match 'up'
      match 'down'
    end
  end

  devise_for :users

  resources :videos do
    member do
      match 'up'
      match 'down'
    end
  end

  resources :photos do
    member do
      match 'up'
      match 'down'
    end
  end

  get "monitor/all"

  get "monitor/online"

  resources :clients do
    resources :records
  end

  mount Outum::API => '/'

  root :to => 'home#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :label, :last_time, :soft_version

  has_many :records, dependent: :destroy
  default_scope order: 'last_time DESC'

  def self.onlines
    all_clients = Client.all
    clients = []
    all_clients.each do |client|
      clients << client if client.record_today
    end
    clients
  end

  def recent_record
    records = self.records.first
  end

  def online_days
    self.records.count
  end

  def recent_city
    # self.recent_record.city if self.recent_record
    record = self.records.where("city <> ''").first
    record.city if record
  end

  def record_today
    self.records.find_by_date(Time.zone.now.to_date)
  end

  def distance_all
    self.records.sum('distance')
  end

  def distance_today
    today_record = record_today
    distance = today_record ? today_record.distance : 0.0
  end

  def duration_all
    self.records.sum('duration')
  end

  def duration_today
    today_record = record_today
    duration = today_record ? today_record.duration : 0.0
  end

  def lat
    # lat = recent_record ? recent_record.lat : nil
    record = self.records.where("lat <> ''").first
    record.lat if record
  end

  def lon
    # lon = recent_record ? recent_record.lon : nil
    record = self.records.where("lon <> ''").first
    record.lon if record
  end

  def as_json(options)
    json_data = {}
    json_data[:label] = label
    json_data[:last_time] = last_time
    json_data[:distance] = distance_today
    json_data[:lat] = lat if lat
    json_data[:lon] = lon if lon
    json_data
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  before_filter :authenticate_user!
  
  # GET /clients
  # GET /clients.json
  def index
    @controller = controller_name
    @action = action_name
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @controller = controller_name
    @action = action_name
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for @client, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :label, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :label, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_time, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :last_time, :class => 'datetime_select' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                clients_path, :class => 'btn' %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/clients/index.html.erb
<div class="container">
  <ul class="breadcrumb">
    <li><a href="/"><span class="label label-success">主页</span></a><span class="divider">/</span></li>
    <li class="active"><span class="label label-default">客户端统计</span></li>
  </ul>
  <div id="counter"></div>
  <table id="clients" class="table table-striped table-bordered table-hover datatable">
   <thead>
    <tr>
      <th>序列号</th>
      <th>所在城市</th>
      <th>软件版本号</th>
      <th>最后上线时间</th>
      <th>在线天数</th>
      <th>今日里程（km）</th>
      <th>今日在线时长（分）</th>
      <th>总里程（km）</th>
      <th>总在线时长（分）</th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
    <tr>
      <td><%= link_to client.label, client_path(client), :class => "badge badge-info" %></td>
      <!-- <td><%= link_to client.label, "##{client.label}", :class => "badge badge-info", :data => {:toggle=>"modal"}  %></td> -->
      <td><%= client.recent_city.to_s %></td>
      <td><%= client.soft_version.to_s %></td>
      <td><%= "#{client.last_time}(#{time_ago_in_words(client.last_time)}前)" %></td>
      <td><%= client.online_days %>天</td>
      <td><%= (client.distance_today / 1000).round(2) %></td>
      <td><%= (client.duration_today / 60).round(2) %></td>
      <td><%= (client.distance_all / 1000).round(2) %></td>
      <td><%= (client.duration_all / 60).round(2) %></td>
    </tr>
    <% end %>
  </tbody>
</table> 
</div>

app/views/clients/new.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/clients/show.html.erb
<%- model_class = Client -%>

<ul class="breadcrumb">
  <li><a href="/"><span class="label label-success">主页</span></a> <span class="divider">/</span></li>
  <li><a href="/clients/"><span class="label label-info">客户端统计</span></a> <span class="divider">/</span></li>
  <li class="active"><span class="label label-default"><%= @client.label %></span></li>
</ul>

<dl class="dl-horizontal">
  <dt><strong>序列号</strong></dt>
  <dd><%= @client.label %></dd>
  <dt><strong>在线天数</strong></dt>
  <dd><%= @client.online_days %></dd>
  <dt><strong>最后上线时间</strong></dt>
  <dd><%= @client.last_time %></dd>
  <dt><strong>所在城市</strong></dt>
  <dd><%= @client.recent_city.to_s %></dd>
  <dt><strong>今日里程（km）</strong></dt>
  <dd><%= (@client.distance_today / 1000).round(2) %></dd>
  <dt><strong>今日在线时长（分）</strong></dt>
  <dd><%= (@client.duration_today / 60).round(2) %></dd>
  <dt><strong>总里程（km）</strong></dt>
  <dd><%= (@client.distance_all / 1000).round(2) %></dd>
  <dt><strong>总在线时长（分）</strong></dt>
  <dd><%= (@client.duration_all / 60).round(2) %></dd>
  <dt><strong>软件版本号</strong></dt>
  <dd><%= @client.soft_version.to_s %></dd>
</dl>

<% if @client.records.length > 0 %>
  <table id="records" class="table table-striped table-bordered table-hover datatable">
    <thead>
      <tr>
        <th>所在城市</th>
        <th>日期</th>
        <th>终端类型</th>
        <th>终端IMEI</th>
        <th>当日里程（km）</th>
        <th>当日在线时长（分）</th>
        <th>最后在线时间</th>
      </tr>
    </thead>
    <tbody>

      <% @client.records.each do |record| %>
        <tr>
          <td><%= record.city %></td>
          <td><%= record.date %></td>
          <td><%= record.ue %></td>
          <td><%= record.imei %></td>
          <td><%= (record.distance / 1000).round(2) %></td>
          <td><%= (record.duration / 60).round(2) %></td>
          <td><%= record.last_time %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>