config/routes.rb
OutumMonitor::Application.routes.draw do
  get "home/version"
  get "home/index"
  get "home/patch"

  resources :products do
    member do
      match 'download'
      match 'up'
      match 'down'
    end
  end

  devise_for :users

  resources :videos do
    member do
      match 'up'
      match 'down'
    end
  end

  resources :photos do
    member do
      match 'up'
      match 'down'
    end
  end

  get "monitor/all"

  get "monitor/online"

  resources :clients do
    resources :records
  end

  mount Outum::API => '/'

  root :to => 'home#index'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :note, :title
  has_one :attachment, as: :attachmentable, dependent: :destroy
  
  acts_as_list
  default_scope order('position')
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  before_filter :authenticate_user!

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        Attachment.create(media: params[:attachment], attachmentable: @photo) if params[:attachment]
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photo/1/up
  def up
    @photo = Photo.find(params[:id])
    @photo.move_higher
    
    respond_to do |format|
      format.html { redirect_to photos_url, notice: "Photo #{@photo.title} was successfully moved." }
    end
  end
  
  # PUT /photo/1/down
  def down
    @photo = Photo.find(params[:id])
    @photo.move_lower
    
    respond_to do |format|
      format.html { redirect_to photos_url, notice: "Photo #{@photo.title} position was successfully moved." }
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])
    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        if params[:attachment]
          @photo.attachment.delete if @photo.attachment
          Attachment.create(media: params[:attachment], attachmentable: @photo)
        end
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for @photo, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :note, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :note, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :attachment, :class => 'control-label' %>
    <div class="controls">
      <%= file_field_tag :attachment%>
      <%= image_tag(@photo.attachment.media.thumb) if @photo.attachment %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                photos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<%- model_class = Photo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/photos/index.html.erb
<%- model_class = Photo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:attachment) %></th>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:note) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= link_to photo.id, photo_path(photo) %></td>
        <td><%= image_tag(photo.attachment.media.thumb) if photo.attachment %></td>
        <td><%= photo.title %></td>
        <td><%= photo.note %></td>
        <td><%=l photo.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_photo_path(photo), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      photo_path(photo),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
          <a class="btn" href="<%= up_photo_path(photo) %>"><i class="icon-arrow-up"></i></a>
          <a class="btn" href="<%= down_photo_path(photo) %>"><i class="icon-arrow-down"></i></a>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_photo_path,
            :class => 'btn btn-primary' %>

app/views/photos/new.html.erb
<%- model_class = Photo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/photos/show.html.erb
<%- model_class = Photo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @photo.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:note) %>:</strong></dt>
  <dd><%= @photo.note %></dd>
  <dt><strong><%= model_class.human_attribute_name(:attachment) %>:</strong></dt>
  <dd><%= image_tag @photo.attachment.media.preview if @photo.attachment %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              photos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_photo_path(@photo), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              photo_path(@photo),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>