config/routes.rb
OutumMonitor::Application.routes.draw do
  get "home/version"
  get "home/index"
  get "home/patch"

  resources :products do
    member do
      match 'download'
      match 'up'
      match 'down'
    end
  end

  devise_for :users

  resources :videos do
    member do
      match 'up'
      match 'down'
    end
  end

  resources :photos do
    member do
      match 'up'
      match 'down'
    end
  end

  get "monitor/all"

  get "monitor/online"

  resources :clients do
    resources :records
  end

  mount Outum::API => '/'

  root :to => 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :attachment, :download_count, :release_date, :release_note, :statble, :release_version

  has_one :attachment, as: :attachmentable, dependent: :destroy

  acts_as_list
  default_scope order('position desc')

  def self.stables
    where(statble: false)
  end

  def self.patches
    where(statble: true)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :authenticate_user!, only: [:index, :edit, :new]
  
  # GET /products/1/download
  def download
    @product = Product.find(params[:id])
    send_file @product.attachment.media.current_path
  end

  # PUT /product/1/up
  def up
    @product = Product.find(params[:id])
    @product.move_lower
    
    respond_to do |format|
      format.html { redirect_to products_url, notice: "product position was successfully moved." }
    end
  end
  
  # PUT /product/1/down
  def down
    @product = Product.find(params[:id])
    @product.move_higher
    
    respond_to do |format|
      format.html { redirect_to products_url, notice: "product position was successfully moved." }
    end
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])
    @product.release_date = Time.zone.now.to_date

    respond_to do |format|
      if @product.save
        Attachment.create(media: params[:attachment], attachmentable: @product) if params[:attachment]
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        if params[:attachment]
          @product.attachment.delete if @product.attachment
          Attachment.create(media: params[:attachment], attachmentable: @product)
        end
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
  <div class="control-group">
    <%= f.label "版本号", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :release_version, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "发布说明", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :release_note, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "版本附件", :class => 'control-label' %>
    <div class="controls">
      <%= file_field_tag :attachment %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "是否补丁版本", :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :statble, :class => 'check_box' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:release_version) %></th>
      <th><%= model_class.human_attribute_name(:release_note) %></th>
      <th><%= model_class.human_attribute_name(:release_date) %></th>
      <th><%= model_class.human_attribute_name(:attachment) %></th>
      <th><%= "是否补丁版本" %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.id, product_path(product) %></td>
        <td><%= product.release_version %></td>
        <td><%= truncate product.release_note, length: 15 %></td>
        <td><%= product.release_date %></td>
        <td><%= product.attachment.file_name %></td>
        <td><%= product.statble %></td>
        <td><%=l product.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
          <a class="btn" href="<%= up_product_path(product) %>"><i class="icon-arrow-up"></i></a>
          <a class="btn" href="<%= down_product_path(product) %>"><i class="icon-arrow-down"></i></a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' %>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:release_version) %>:</strong></dt>
  <dd><%= @product.release_version %></dd>
  <dt><strong><%= model_class.human_attribute_name(:release_note) %>:</strong></dt>
  <dd><%= @product.release_note %></dd>
  <dt><strong><%= model_class.human_attribute_name(:release_date) %>:</strong></dt>
  <dd><%= @product.release_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:attachment) %>:</strong></dt>
  <dd><%= link_to "download", download_product_path(@product) %></dd>
  <dt><strong><%= "是否补丁版本" %>:</strong></dt>
  <dd><%= @product.statble.to_s %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>